{
  "openapi": "3.0.0",
  "info": {
    "title": "API-MATERIAISEBENS-BENSCONSOLIDADOS",
    "description": "Com base no ano, parâmetro obrigatório, a API irá recuperar os Bens Consolidados da Administração Pública da Prefeitura Municipal de Lajinha - MG.     <table>\n  <thead>\n    <tr>\n      <th>Versão</th>\n      <th>Elaborado por</th>\n      <th>Data</th>\n      <th>Alterações</th>\n    </tr>\n  </thead>  \n  <tbody>\n    <tr>  \n      <td>1.0.0</td>\n      <td>Regiane Brito</td>\n      <td>2022-03-28</td>\n      <td>[MATERIAIS E BENS] - Versão inicial</td> \n    </tr> \n  </tbody>\n</table>\n\n\n\n## Objetivo\n\n  O Objetivo dessa API é consultar na área de Materiais e Bens os Bens Consolidados quer sejam imóveis, móveis, intangíveis ou semoventes, que pertencem ao domínio da Administração Pública.  \n  \n\n## Público-Alvo\n\n  A Prefeitura Municipal de Lajinha – MG, dispõe as informações a serem consultadas, através do Portal da Transparência, disponibilizando a qualquer interessado as informações a serem consultadas nessa API. \n  \n## Provedores\n\n O Portal da Transparência da Prefeitura Municipal de Lajinha - MG \n\n## Contexto em que a API se Insere\n\n Prezando pela transparência nos dados, a API será disponibilizada para que qualquer cidadão possa consultar os bens da Administração Pública.",
    "version": "1;2022-04-26",
    "contact": {
      "name": "Regiane Brito",
      "email": "email@email.com.br"
    },
    "x-domains": [
      "Administração Pública"
    ]
  },
  "security": [
    {
      "BasicAuth": []
    },
    {
      "BearerAuth": []
    },
    {
      "ApiKeyAuth": []
    },
    {
      "OAuth2": []
    }
  ],
  "paths": {
    "/bens_consolidados": {
      "get": {
        "x-lajinha-backends": [
          "Portal da Transparência Prefeitura Municipal Lajinha - MG"
        ],
        "x-lajinha-domains": [
          "Portal da Transparência Prefeitura Municipal Lajinha - MG"
        ],
        "summary": "Operação de consulta a conjunto de bens consolidados do domínio da Administração Pública",
        "description": "Esse metodo tem como objetivo fazer uma consulta de Bens Consolidados no Portal da Transparência Prefeitura Municipal Lajinha - MG obtendo assim informações dos bens como ano, unidade gestora, categoria e outros",
        "tags": [
          "Bens Consolidados"
        ],
        "parameters": [
          {
            "name": "ano",
            "in": "query",
            "required": true,
            "description": "Ano do exercício a ser consultado.",
            "example": "2017",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Objeto de negócio contendo os dados retornados pela API.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response200"
                },
                "example": {
                  "apiVersion": "1;2022-03-28",
                  "transactionId": "",
                  "data": [
                    {
                      "ano": "2017",
                      "unidade_gestora": "PREFEITURA MUNICIPAL DE LAJINHA",
                      "data": "2017-08-17T00:00:00",
                      "categoria": "Bens MOVEIS",
                      "tipo": "Aquisicao",
                      "controle": "501000018",
                      "especificacao": "CABO USB PARA IMPRESSORA",
                      "descricao": "",
                      "localizacao": "AGRICULTURA",
                      "valor": 20
                    },
                    {
                      "ano": "2017",
                      "unidade_gestora": "PREFEITURA MUNICIPAL DE LAJINHA",
                      "data": "2017-08-17T00:00:00",
                      "categoria": "Bens MOVEIS",
                      "tipo": "Baixas",
                      "controle": "501000018",
                      "especificacao": "CABO USB PARA IMPRESSORA",
                      "descricao": "",
                      "localizacao": "AGRICULTURA",
                      "valor": 20
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "401": {
            "$ref": "#/components/responses/401"
          },
          "403": {
            "$ref": "#/components/responses/403"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "405": {
            "$ref": "#/components/responses/405"
          },
          "406": {
            "$ref": "#/components/responses/406"
          },
          "409": {
            "$ref": "#/components/responses/409"
          },
          "410": {
            "$ref": "#/components/responses/410"
          },
          "415": {
            "$ref": "#/components/responses/415"
          },
          "422": {
            "$ref": "#/components/responses/422"
          },
          "429": {
            "$ref": "#/components/responses/429"
          },
          "500": {
            "$ref": "#/components/responses/500"
          },
          "503": {
            "$ref": "#/components/responses/503"
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "https://6096015d116f3f00174b29ba.mockapi.io/",
      "description": "API Bens Consolidados"
    }
  ],
  "components": {
    "securitySchemes": {
      "BasicAuth": {
        "type": "http",
        "scheme": "basic"
      },
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer"
      },
      "ApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "X-API-Key"
      },
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/oauth2/v1/token",
            "scopes": {}
          }
        }
      }
    },
    "schemas": {
      "apiVersion": {
        "type": "string",
        "description": "Retorna sempre a versão major e minor da API efetivamente consumida. O formato é “versão major;versão minor”. Exemplo: \"apiVersion: 2;2015-08-12\". Quando a versão minor não é solicitada, a versão contratada pelo cliente é retornada. Quando não há restrição de contratação, retorna a última disponível.",
        "example": "1;2022-03-28"
      },
      "transactionId": {
        "type": "string",
        "description": "Retorna o identificador de rastreabilidade de transação gerado pela API.",
        "example": ""
      },
      "error": {
        "description": "Objeto retornado na ocorrência de algum erro (4xx/5xx).",
        "type": "object",
        "required": [
          "apiVersion",
          "transactionId",
          "error"
        ],
        "properties": {
          "apiVersion": {
            "$ref": "#/components/schemas/apiVersion"
          },
          "transactionId": {
            "$ref": "#/components/schemas/transactionId"
          },
          "error": {
            "type": "object",
            "properties": {
              "httpCode": {
                "type": "string",
                "description": "Código de erro HTTP."
              },
              "errorCode": {
                "type": "string",
                "description": "Código de erro interno da API no formato. Ex.: API-3566. Esse código poderá ser utilizado internamente pelo cliente para mapeamento customizado da mensagem de erro."
              },
              "message": {
                "type": "string",
                "description": "Mensagem de erro resumida."
              },
              "detailedMessage": {
                "type": "string",
                "description": "Mensagem de erro detalhada."
              },
              "link": {
                "type": "object",
                "description": "Objeto para conter o link para a página com a documentação detalhada dos códigos e descrições dos erros",
                "properties": {
                  "rel": {
                    "type": "string",
                    "enum": [
                      "related"
                    ],
                    "description": "Para referenciar a página de erros do API portal será utilizada a semântica \"related\" nesse cenário."
                  },
                  "href": {
                    "type": "string",
                    "description": "URL completa do recurso."
                  }
                }
              }
            }
          }
        }
      },
      "Response200": {
        "description": "Objeto responsável por representar o retorno ao consumidor.",
        "type": "object",
        "required": [
          "apiVersion",
          "transactionId",
          "data"
        ],
        "properties": {
          "apiVersion": {
            "$ref": "#/components/schemas/apiVersion"
          },
          "transactionId": {
            "$ref": "#/components/schemas/transactionId"
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "ano": {
                  "type": "string",
                  "description": "Ano da ocorência."
                },
                "unidadeGestora": {
                  "type": "string",
                  "description": "Nome da unidade gestora proprietária do bem."
                },
                "data": {
                  "type": "string",
                  "description": "Data da incorporação do bem."
                },
                "categoria": {
                  "type": "string",
                  "description": "Categoria do bem."
                },
                "tipo": {
                  "type": "string",
                  "description": "Tipo do bem."
                },
                "controle": {
                  "type": "string",
                  "description": "Número de controle do bem."
                },
                "especificacao": {
                  "type": "string",
                  "description": "Especificação do bem."
                },
                "descricao": {
                  "type": "string",
                  "description": "Descrição detalhada do bem."
                },
                "localizacao": {
                  "type": "string",
                  "description": "Secretaria/órgão ou local onde o bem esta localizado."
                },
                "valor": {
                  "type": "string",
                  "description": "Valor do bem."
                }
              }
            }
          }
        }
      }
    },
    "responses": {
      "400": {
        "description": "Bad Request",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "examples": {
              "BadRequest": {
                "value": {
                  "apiVersion": "1;2022-03-28",
                  "transactionId": "",
                  "error": {
                    "httpCode": "400",
                    "errorCode": "API-MATERIAISEBENS-BENSCONSOLIDADOS-400",
                    "message": "Bad Request",
                    "detailedMessage": "Invalid Request for operation.",
                    "link": {
                      "rel": "related",
                      "href": "https://lajinha-mg.portaltp.com.br"
                    }
                  }
                }
              },
              "RequireFieldsFault": {
                "value": {
                  "apiVersion": "1;2022-03-28",
                  "transactionId": "593f33f6-6122-4624-8c1c-6602a14a730e",
                  "error": {
                    "httpCode": "400",
                    "errorCode": "API-MATERIAISEBENS-BENSCONSOLIDADOS-400",
                    "message": "Bad Request",
                    "detailedMessage": "O campo [nome_campo] é obrigatório.",
                    "link": {
                      "rel": "related",
                      "href": "https://lajinha-mg.portaltp.com.br"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "401": {
        "description": "Unauthorized",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "",
              "error": {
                "httpCode": "401",
                "errorCode": "API-MATERIAISEBENS-BENSCONSOLIDADOS-401",
                "message": "Unauthorized",
                "detailedMessage": "Unauthorized",
                "link": {
                  "rel": "related",
                  "href": "https://lajinha-mg.portaltp.com.br"
                }
              }
            }
          }
        }
      },
      "403": {
        "description": "Forbidden",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "",
              "error": {
                "httpCode": "403",
                "errorCode": "API-MATERIAISEBENS-BENSCONSOLIDADOS-403",
                "message": "Forbidden",
                "detailedMessage": "Access denied.",
                "link": {
                  "rel": "related",
                  "href": "https://lajinha-mg.portaltp.com.br"
                }
              }
            }
          }
        }
      },
      "404": {
        "description": "Not Found",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "",
              "error": {
                "httpCode": "404",
                "errorCode": "API-MATERIAISEBENS-BENSCONSOLIDADOS-404",
                "message": "Not found",
                "detailedMessage": "Resource not found.",
                "link": {
                  "rel": "related",
                  "href": "https://lajinha-mg.portaltp.com.br"
                }
              }
            }
          }
        }
      },
      "405": {
        "description": "Method Not Allowed",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "",
              "error": {
                "httpCode": "405",
                "errorCode": "API-MATERIAISEBENS-BENSCONSOLIDADOS-405",
                "message": "Method Not Allowed",
                "detailedMessage": "Unavailable HTTP method.",
                "link": {
                  "rel": "related",
                  "href": "https://lajinha-mg.portaltp.com.br"
                }
              }
            }
          }
        }
      },
      "406": {
        "description": "Not Acceptable",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "",
              "error": {
                "httpCode": "406",
                "errorCode": "API-MATERIAISEBENS-BENSCONSOLIDADOS-406",
                "message": "Request Not Acceptable",
                "detailedMessage": "Requested content type not acceptable.",
                "link": {
                  "rel": "related",
                  "href": "https://lajinha-mg.portaltp.com.br"
                }
              }
            }
          }
        }
      },
      "409": {
        "description": "Resource not available",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2021-08-18",
              "transactionId": "",
              "error": {
                "httpCode": "409",
                "errorCode": "API-MATERIAISEBENS-BENSCONSOLIDADOS-409",
                "message": "RESOURCE_NOT_AVAILABLE",
                "detailedMessage": "There is no port available.",
                "link": {
                  "rel": "related",
                  "href": "https://lajinha-mg.portaltp.com.br"
                }
              }
            }
          }
        }
      },
      "410": {
        "description": "Gone",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "",
              "error": {
                "httpCode": "410",
                "errorCode": "API-MATERIAISEBENS-BENSCONSOLIDADOS-410",
                "message": "Resource Unavailable",
                "detailedMessage": "The resource is no longer available.",
                "link": {
                  "rel": "related",
                  "href": "https://lajinha-mg.portaltp.com.br"
                }
              }
            }
          }
        }
      },
      "415": {
        "description": "Unsupported Media Type",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "",
              "error": {
                "httpCode": "415",
                "errorCode": "API-MATERIAISEBENS-BENSCONSOLIDADOS-415",
                "message": "Unsupported Media Type",
                "detailedMessage": "Unsupported request media type.",
                "link": {
                  "rel": "related",
                  "href": "https://lajinha-mg.portaltp.com.br"
                }
              }
            }
          }
        }
      },
      "422": {
        "description": "Unprocessable Entity",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "examples": {
              "UnprocessablEntityFault": {
                "value": {
                  "apiVersion": "1;2021-08-15",
                  "transactionId": "593f33f6-6122-4624-8c1c-6602a14a730e",
                  "error": {
                    "httpCode": "422",
                    "errorCode": "API-MATERIAISEBENS-BENSCONSOLIDADOS-422",
                    "message": "Unprocessable Entity",
                    "detailedMessage": "Business fault occurred.",
                    "link": {
                      "rel": "related",
                      "href": "https://lajinha-mg.portaltp.com.br"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "429": {
        "description": "Too Many Requests",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "",
              "error": {
                "httpCode": "429",
                "errorCode": "API-MATERIAISEBENS-BENSCONSOLIDADOS-429",
                "message": "Too Many Requests",
                "detailedMessage": "Consumer requests exceeded policies.",
                "link": {
                  "rel": "related",
                  "href": "https://lajinha-mg.portaltp.com.br"
                }
              }
            }
          }
        }
      },
      "451": {
        "description": "Unavailable For Legal Reasons",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "",
              "error": {
                "httpCode": "451",
                "errorCode": "API-MATERIAISEBENS-BENSCONSOLIDADOS-451",
                "message": "Unavailable For Legal Reasons",
                "detailedMessage": "Unavailable For Legal Reasons.",
                "link": {
                  "rel": "related",
                  "href": "https://lajinha-mg.portaltp.com.br"
                }
              }
            }
          }
        }
      },
      "500": {
        "description": "Internal Server Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "examples": {
              "internalServerError": {
                "value": {
                  "apiVersion": "1;2022-03-28",
                  "transactionId": "",
                  "error": {
                    "httpCode": "500",
                    "errorCode": "API-MATERIAISEBENS-BENSCONSOLIDADOS-500",
                    "message": "Internal Server Error",
                    "detailedMessage": "Internal Server Error.",
                    "link": {
                      "rel": "related",
                      "href": "https://lajinha-mg.portaltp.com.br"
                    }
                  }
                }
              },
              "technicalFault": {
                "value": {
                  "apiVersion": "1;2022-03-28",
                  "transactionId": "",
                  "error": {
                    "httpCode": "500",
                    "errorCode": "API-MATERIAISEBENS-BENSCONSOLIDADOS-503",
                    "message": "Internal Server Error",
                    "detailedMessage": "Falha Técnica.",
                    "link": {
                      "rel": "related",
                      "href": "https://lajinha-mg.portaltp.com.br"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "503": {
        "description": "Service unavailable",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "",
              "error": {
                "httpCode": "503",
                "errorCode": "API-MATERIAISEBENS-BENSCONSOLIDADOS-503",
                "message": "Service Unavailable",
                "detailedMessage": "Service Unavailable.",
                "link": {
                  "rel": "related",
                  "href": "https://lajinha-mg.portaltp.com.br"
                }
              }
            }
          }
        }
      }
    }
  }
}
