{
  "openapi": "3.0.0",
  "info": {
    "title": "Payments - Query Transaction Details",
    "description": "Com base nos parâmetros e-mail, token e código da transação, será possível consultar detalhes da transação realizada. <table>\n  <thead>\n    <tr>\n      <th>Versão</th>\n      <th>Elaborado por</th>\n      <th>Data</th>\n      <th>Alterações</th>\n    </tr>\n  </thead>  \n  <tbody>\n    <tr>  \n      <td>1.0.0</td>\n      <td>Regiane Brito</td>\n      <td>2022-04-25</td>\n      <td>[TRANSPARENT CHECKOUT] - Versão inicial</td> \n    </tr> \n  </tbody>\n</table>\n\n\n\n## Objetivo\n\n  O Objetivo dessa API é permitir após a validação dos dados requisitados (e-mail, token e código da transação) detalhes da transação, do link do pagamento, identificação do comprador e dados pessoais.\n  \n\n## Público-Alvo\n\n  Comerciantes interessados no uso do Checkout Transparente para pagamentos através de Boleto, Débito Online ou Cartão de Crédito.\n  \n## Provedores\n\n BackEnd Checkout Transparente - PagSeguro\n\n## Contexto em que a API se Insere\n\n O PagSeguro disponibiliza a documentação de API´s para que através do Checkout Transparente sejam efetuados pagamentos através dos seguintes meios: Boleto, Débito Online ou Cartão de Crédito.\n ",
    "version": "1;2022-04-26",
    "contact": {
      "name": "Regiane Brito",
      "email": "email@dominio.com.br"
    },
    "x-PagSeguro-domains": [
      "Checkout"
    ]
  },
  "security": [
    {
      "BasicAuth": []
    },
    {
      "BearerAuth": []
    },
    {
      "ApiKeyAuth": []
    },
    {
      "OAuth2": []
    }
  ],
  "paths": {
    "/transactionsdetails": {
      "get": {
        "x-pagseguro-backends": [
          "Providers Redirect Checkout"
        ],
        "x-pagseguro-domains": "Transparent Checkout",
        "summary": "Com base nos parâmetros requisitados a API irá retornar detalhes da transação solicitada.",
        "description": "Esse metodo tem como objetivo fazer uma consulta aos detalhes da transação solicitada. ",
        "tags": [
          "Query Transaction Details"
        ],
        "parameters": [
          {
            "name": "X-QueryString",
            "in": "header",
            "required": true,
            "description": "**Para o acesso aos detalhes da transação serão necessários a identificação das seguintes informações:**\n* E-mail da conta cadastrada\n* Token gerado para conta cadastrada\n* Código da transação que será consultada",
            "example": "email=email@email.com&token=token&transactionCode=2504A4D645CD4EFCA3EA6DE8034FB945",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Objeto de negócio contendo os dados retornados pela API.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response200"
                },
                "example": {
                  "apiVersion": "1;2022-03-28",
                  "transactionId": "593f33f6-6122-4624-8c1c-6602a14a730e",
                  "data": {
                    "date": "2017-12-04T17:19:31.000-02:00",
                    "code": "79E53362-F6B2-4DFF-B3FD-23B4E0C19B35",
                    "reference": "REF1234",
                    "type": "1",
                    "status": "1",
                    "lastEventDate": "2017-12-04T17:19:32.000-02:00",
                    "paymentMethod": {
                      "type": "2",
                      "code": "202"
                    },
                    "paymentLink": "https://pagseguro.uol.com.br/checkout/payment/booklet/print.jhtml?c=62238ca9db0aa8913528210ce3d7c7d4e72d138f985eb97976d39013d22fed1283fc0072edc1a23c",
                    "grossAmount": "998.98",
                    "discountAmount": "0.00",
                    "creditorFees": {
                      "operationalFeeAmount": "1.00",
                      "intermediationRateAmount": "0.40",
                      "intermediationFeeAmount": "39.82"
                    },
                    "netAmount": "957.76",
                    "extraAmount": "-0.01",
                    "installmentCount": "1",
                    "itemCount": "2",
                    "items": [
                      {
                        "id": "0001",
                        "description": "Notebook Prata",
                        "quantity": "1",
                        "amount": "998.98"
                      },
                      {
                        "id": "0002",
                        "description": "Notebook Rosa",
                        "quantity": "1",
                        "amount": "0.01"
                      }
                    ],
                    "sender": {
                      "name": "Jose Comprador",
                      "email": "jose@dominio.com.br",
                      "phone": {
                        "areaCode": "11",
                        "number": "56713293"
                      }
                    },
                    "primaryReceiver": {
                      "publicKey": "PUB175E07D7FB62462BAE3C9A60EA1B32AE"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "401": {
            "$ref": "#/components/responses/401"
          },
          "403": {
            "$ref": "#/components/responses/403"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "405": {
            "$ref": "#/components/responses/405"
          },
          "406": {
            "$ref": "#/components/responses/406"
          },
          "422": {
            "$ref": "#/components/responses/422"
          },
          "429": {
            "$ref": "#/components/responses/429"
          },
          "500": {
            "$ref": "#/components/responses/500"
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "https://6096015d116f3f00174b29ba.mockapi.io/payments",
      "description": "API Checkout Transparente"
    }
  ],
  "components": {
    "securitySchemes": {
      "BasicAuth": {
        "type": "http",
        "scheme": "basic"
      },
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer"
      },
      "ApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "X-API-Key"
      },
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/oauth2/v1/token",
            "scopes": {}
          }
        }
      }
    },
    "schemas": {
      "apiVersion": {
        "type": "string",
        "description": "Retorna sempre a versão major e minor da API efetivamente consumida. O formato é “versão major;versão minor”. Exemplo: \"apiVersion: 2;2015-08-12\". Quando a versão minor não é solicitada, a versão contratada pelo cliente é retornada. Quando não há restrição de contratação, retorna a última disponível.",
        "example": "1;2022-03-28"
      },
      "transactionId": {
        "type": "string",
        "description": "Retorna o identificador de rastreabilidade de transação gerado pela API.",
        "example": "593f33f6-6122-4624-8c1c-6602a14a730e"
      },
      "error": {
        "description": "Objeto retornado na ocorrência de algum erro (4xx/5xx).",
        "type": "object",
        "required": [
          "apiVersion",
          "transactionId",
          "error"
        ],
        "properties": {
          "apiVersion": {
            "$ref": "#/components/schemas/apiVersion"
          },
          "transactionId": {
            "$ref": "#/components/schemas/transactionId"
          },
          "error": {
            "type": "object",
            "properties": {
              "httpCode": {
                "type": "string",
                "description": "Código de erro HTTP."
              },
              "errorCode": {
                "type": "string",
                "description": "Código de erro interno da API no formato. Ex.: API-3566. Esse código poderá ser utilizado internamente pelo cliente para mapeamento customizado da mensagem de erro."
              },
              "message": {
                "type": "string",
                "description": "Mensagem de erro resumida."
              },
              "detailedMessage": {
                "type": "string",
                "description": "Mensagem de erro detalhada."
              },
              "link": {
                "type": "object",
                "description": "Objeto para conter o link para a página com a documentação detalhada dos códigos e descrições dos erros no API portal.",
                "properties": {
                  "rel": {
                    "type": "string",
                    "enum": [
                      "related"
                    ],
                    "description": "Para referenciar a página de erros do API portal será utilizada a semântica \"related\" nesse cenário."
                  },
                  "href": {
                    "type": "string",
                    "description": "URL completa do recurso."
                  }
                }
              }
            }
          }
        }
      },
      "Response200": {
        "description": "Objeto responsável por representar o retorno ao consumidor.",
        "type": "object",
        "required": [
          "apiVersion",
          "transactionId",
          "data"
        ],
        "properties": {
          "apiVersion": {
            "$ref": "#/components/schemas/apiVersion"
          },
          "transactionId": {
            "$ref": "#/components/schemas/transactionId"
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "startDate": {
                  "type": "string",
                  "description": "Data da criação da transação. Informa o momento em que a transação foi criada."
                },
                "code": {
                  "type": "string",
                  "description": "Código identificador da transação. Retorna o código que identifica a transação de forma única."
                },
                "reference": {
                  "type": "string",
                  "description": "Código de referência da transação. Informa o código que foi usado para fazer referência ao pagamento. Este código foi fornecido no momento do pagamento e é útil para vincular as transações do PagSeguro às vendas registradas no seu sistema."
                },
                "typeId": {
                  "type": "string",
                  "description": "Tipo da transação. Representa o tipo da transação recebida. Os valores mais comuns para este campo e seus respectivos resultados são descritos abaixo."
                },
                "status": {
                  "type": "string",
                  "description": "Status da transação. Informa o código representando o status da transação, permitindo que você decida se deve liberar ou não os produtos ou serviços adquiridos."
                },
                "endDate": {
                  "type": "string",
                  "description": "Data do último evento. Informa o momento em que ocorreu a última alteração no status da transação."
                },
                "paymentMethod": {
                  "type": "object",
                  "properties": {
                    "payMethodType": {
                      "type": "string",
                      "description": "Tipo do meio de pagamento. Informa o tipo do meio de pagamento usado pelo comprador. Este tipo agrupa diversos meios de pagamento e determina de forma geral o comportamento da transação."
                    },
                    "code": {
                      "type": "string",
                      "description": "Código identificador do meio de pagamento. Informa um código que identifica o meio de pagamento usado pelo comprador. O meio de pagamento descreve a bandeira de cartão de crédito utilizada ou banco escolhido para um débito online."
                    }
                  }
                },
                "paymentLink": {
                  "type": "string",
                  "description": "Link para o Pagamento. Informa a URL para a exibição do boleto ou, quando o meio de pagamento for TEF, a URL para abrir o pop-up do banco. Quando o meio de pagamento for Cartão de crédito este parâmetro será omitido."
                },
                "grossAmount": {
                  "type": "string",
                  "description": "Valor bruto da transação. Informa o valor bruto da transação, calculado pela soma dos preços de todos os itens presentes no pagamento."
                },
                "discountAmount": {
                  "type": "string",
                  "description": "Valor do desconto dado. Informa o valor do desconto dado a compradores que optaram por pagar com débito online ou boleto. Este desconto aplica-se quando você opta por incluir no preço dos produtos o custo do parcelamento de pagamentos com cartão de crédito. O desconto é dado para não onerar os compradores que optaram por meios à vista."
                },
                "creditorFees": {
                  "type": "object",
                  "properties": {
                    "operationalFeeAmount": {
                      "type": "string",
                      "description": "Valor total das taxas cobradas. Informa o valor total das taxas cobradas pelo PagSeguro nesta transação."
                    },
                    "intermediationRateAmount": {
                      "type": "string",
                      "description": " Valor da taxa de intermediação cobradas pelo PagSeguro nesta transação."
                    },
                    "intermediationFeeAmount": {
                      "type": "string",
                      "description": "Valor total da taxa de intermediação cobradas pelo PagSeguro nesta transação. "
                    }
                  }
                },
                "netAmount": {
                  "type": "string",
                  "description": "Valor líquido da transação. Informa o valor líquido da transação, que corresponde ao valor bruto, menos o valor das taxas. Caso presente, o valor de extraAmount (que pode ser positivo ou negativo) também é considerado no cálculo."
                },
                "extraAmount": {
                  "type": "string",
                  "description": "Valor extra. Informa um valor extra que foi somado ou subtraído do valor pago pelo comprador. Este valor é especificado por você no pagamento e pode representar um valor que você quer cobrar separadamente do comprador ou um desconto que quer dar a ele."
                },
                "installmentCount": {
                  "type": "string",
                  "description": "Número de parcelas. Indica o número de parcelas que o comprador escolheu no pagamento com cartão de crédito."
                },
                "itemCount": {
                  "type": "string",
                  "description": "Número de itens da transação. Aponta o número de itens contidos nesta transação."
                },
                "items": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "description": "Identificador do item. Identifica o item da transação. Este identificador deve ser único por transação e foi informado por você no fluxo de pagamento."
                    },
                    "description": {
                      "type": "string",
                      "description": "Descrição do item. Descreve o item da transação. A descrição é um texto explicativo do item que você especificou no fluxo de pagamento."
                    },
                    "quantity": {
                      "type": "string",
                      "description": "Quantidade do item. Informa a quantidade do item da transação. Está é a quantidade que foi especificada no fluxo de pagamento."
                    },
                    "amount": {
                      "type": "string",
                      "description": "Valor unitário do item. Informa o preço unitário do item da transação. Este é o valor que foi especificado no fluxo de pagamento."
                    }
                  }
                },
                "senderId": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string",
                      "description": "Nome completo do comprador. Informa o nome completo do comprador que realizou o pagamento."
                    },
                    "email": {
                      "type": "string",
                      "description": "E-mail do comprador. Informa o e-mail do comprador que realizou a transação."
                    },
                    "phoneNumber": {
                      "type": "object",
                      "properties": {
                        "areaCode": {
                          "type": "string",
                          "description": "DDD do comprador. Informa o código de área (DDD) do comprador que realizou o pagamento."
                        },
                        "number": {
                          "type": "string",
                          "description": "Número de telefone do comprador. Informa o número do telefone do comprador que realizou o pagamento."
                        }
                      }
                    }
                  }
                },
                "primaryReceiver": {
                  "type": "object",
                  "properties": {
                    "publicKey": {
                      "type": "string",
                      "description": "Identificação principal do recebimento."
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "responses": {
      "400": {
        "description": "Bad Request",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "examples": {
              "BadRequest": {
                "value": {
                  "apiVersion": "1;2022-03-28",
                  "transactionId": "593f33f6-6122-4624-8c1c-6602a14a730e",
                  "error": {
                    "httpCode": "400",
                    "errorCode": "QUERYTRANSACTIONDETAILS-400",
                    "message": "Bad Request",
                    "detailedMessage": "Invalid Request for operation.",
                    "link": {
                      "rel": "related",
                      "href": "https://dev.pagseguro.uol.com.br/v1.0/docs"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "401": {
        "description": "Unauthorized",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "593f33f6-6122-4624-8c1c-6602a14a730e",
              "error": {
                "httpCode": "401",
                "errorCode": "QUERYTRANSACTIONDETAILS-401",
                "message": "Unauthorized",
                "detailedMessage": "Unauthorized",
                "link": {
                  "rel": "related",
                  "href": "https://dev.pagseguro.uol.com.br/v1.0/docs"
                }
              }
            }
          }
        }
      },
      "403": {
        "description": "Forbidden",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "593f33f6-6122-4624-8c1c-6602a14a730e",
              "error": {
                "httpCode": "403",
                "errorCode": "QUERYTRANSACTIONDETAILS-403",
                "message": "Forbidden",
                "detailedMessage": "Access denied.",
                "link": {
                  "rel": "related",
                  "href": "https://dev.pagseguro.uol.com.br/v1.0/docs"
                }
              }
            }
          }
        }
      },
      "404": {
        "description": "Not Found",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "593f33f6-6122-4624-8c1c-6602a14a730e",
              "error": {
                "httpCode": "404",
                "errorCode": "QUERYTRANSACTIONDETAILS-404",
                "message": "Not found",
                "detailedMessage": "Resource not found.",
                "link": {
                  "rel": "related",
                  "href": "https://dev.pagseguro.uol.com.br/v1.0/docs"
                }
              }
            }
          }
        }
      },
      "405": {
        "description": "Method Not Allowed",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "593f33f6-6122-4624-8c1c-6602a14a730e",
              "error": {
                "httpCode": "405",
                "errorCode": "QUERYTRANSACTIONDETAILS-405",
                "message": "Method Not Allowed",
                "detailedMessage": "Unavailable HTTP method.",
                "link": {
                  "rel": "related",
                  "href": "https://dev.pagseguro.uol.com.br/v1.0/docs"
                }
              }
            }
          }
        }
      },
      "406": {
        "description": "Not Acceptable",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "593f33f6-6122-4624-8c1c-6602a14a730e",
              "error": {
                "httpCode": "406",
                "errorCode": "QUERYTRANSACTIONDETAILS-406",
                "message": "Request Not Acceptable",
                "detailedMessage": "Requested content type not acceptable.",
                "link": {
                  "rel": "related",
                  "href": "https://dev.pagseguro.uol.com.br/v1.0/docs"
                }
              }
            }
          }
        }
      },
      "409": {
        "description": "Resource not available",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2021-08-18",
              "transactionId": "593f33f6-6122-4624-8c1c-6602a14a730e",
              "error": {
                "httpCode": "409",
                "errorCode": "QUERYTRANSACTIONDETAILS-409",
                "message": "RESOURCE_NOT_AVAILABLE",
                "detailedMessage": "There is no port available.",
                "link": {
                  "rel": "related",
                  "href": "https://dev.pagseguro.uol.com.br/v1.0/docs"
                }
              }
            }
          }
        }
      },
      "410": {
        "description": "Gone",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "593f33f6-6122-4624-8c1c-6602a14a730e",
              "error": {
                "httpCode": "410",
                "errorCode": "QUERYTRANSACTIONDETAILS-410",
                "message": "Resource Unavailable",
                "detailedMessage": "The resource is no longer available.",
                "link": {
                  "rel": "related",
                  "href": "https://dev.pagseguro.uol.com.br/v1.0/docs"
                }
              }
            }
          }
        }
      },
      "415": {
        "description": "Unsupported Media Type",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "593f33f6-6122-4624-8c1c-6602a14a730e",
              "error": {
                "httpCode": "415",
                "errorCode": "QUERYTRANSACTIONDETAILS-415",
                "message": "Unsupported Media Type",
                "detailedMessage": "Unsupported request media type.",
                "link": {
                  "rel": "related",
                  "href": "https://dev.pagseguro.uol.com.br/v1.0/docs"
                }
              }
            }
          }
        }
      },
      "422": {
        "description": "Unprocessable Entity",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "examples": {
              "UnprocessablEntityFault": {
                "value": {
                  "apiVersion": "1;2021-08-15",
                  "transactionId": "593f33f6-6122-4624-8c1c-6602a14a730e",
                  "error": {
                    "httpCode": "422",
                    "errorCode": "QUERYTRANSACTIONDETAILS-422",
                    "message": "Unprocessable Entity",
                    "detailedMessage": "invalid transactionCode value: 5F2DD757-2AE9-4BE9-B271-42907ACF2B5",
                    "link": {
                      "rel": "related",
                      "href": "https://dev.pagseguro.uol.com.br/v1.0/docs"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "429": {
        "description": "Too Many Requests",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "593f33f6-6122-4624-8c1c-6602a14a730e",
              "error": {
                "httpCode": "429",
                "errorCode": "QUERYTRANSACTIONDETAILS-429",
                "message": "Too Many Requests",
                "detailedMessage": "Consumer requests exceeded policies.",
                "link": {
                  "rel": "related",
                  "href": "https://dev.pagseguro.uol.com.br/v1.0/docs"
                }
              }
            }
          }
        }
      },
      "451": {
        "description": "Unavailable For Legal Reasons",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "593f33f6-6122-4624-8c1c-6602a14a730e",
              "error": {
                "httpCode": "451",
                "errorCode": "QUERYTRANSACTIONDETAILS-451",
                "message": "Unavailable For Legal Reasons",
                "detailedMessage": "Unavailable For Legal Reasons.",
                "link": {
                  "rel": "related",
                  "href": "https://dev.pagseguro.uol.com.br/v1.0/docs"
                }
              }
            }
          }
        }
      },
      "500": {
        "description": "Internal Server Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "examples": {
              "internalServerError": {
                "value": {
                  "apiVersion": "1;2022-03-28",
                  "transactionId": "593f33f6-6122-4624-8c1c-6602a14a730e",
                  "error": {
                    "httpCode": "500",
                    "errorCode": "QUERYTRANSACTIONDETAILS-500",
                    "message": "Internal Server Error",
                    "detailedMessage": "Internal Server Error.",
                    "link": {
                      "rel": "related",
                      "href": "https://dev.pagseguro.uol.com.br/v1.0/docs"
                    }
                  }
                }
              },
              "technicalFault": {
                "value": {
                  "apiVersion": "1;2022-03-28",
                  "transactionId": "593f33f6-6122-4624-8c1c-6602a14a730e",
                  "error": {
                    "httpCode": "500",
                    "errorCode": "QUERYTRANSACTIONDETAILS-503",
                    "message": "Internal Server Error",
                    "detailedMessage": "Falha Técnica.",
                    "link": {
                      "rel": "related",
                      "href": "https://dev.pagseguro.uol.com.br/v1.0/docs"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "503": {
        "description": "Service unavailable",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "apiVersion": "1;2022-03-28",
              "transactionId": "593f33f6-6122-4624-8c1c-6602a14a730e",
              "error": {
                "httpCode": "503",
                "errorCode": "QUERYTRANSACTIONDETAILS-503",
                "message": "Service Unavailable",
                "detailedMessage": "Service Unavailable.",
                "link": {
                  "rel": "related",
                  "href": "https://dev.pagseguro.uol.com.br/v1.0/docs"
                }
              }
            }
          }
        }
      }
    }
  }
}